### ISSUE TITLE
cannot sign in runalyze

### ISSUE THREAD

**Issue by nicosmaris** [jonasoreland/runnerup#969] opened 2020-09-10 18:11 UTC
Works from mobile chrome but not from runnerup

**Comment by gerhardol** [comment] 2020-09-10 22:33
If this is F-Droid, only the testserver is supported in F-Droid, the service requires a private key that cannot be used with open source.
For the Play variant, direct login works but probably not Goggle/Facebook login

**Comment by nicosmaris** [comment] 2020-09-10 22:35
Yes I am referring to Google SSO

**Comment by gerhardol** [comment] 2020-09-10 22:38
Duplicate of #791

**Closed by gerhardol** 2020-09-10 22:38 UTC
