### ISSUE TITLE
"Bonus-Miles"

### ISSUE THREAD

**Issue by speendo** [jonasoreland/runnerup#319] opened 2015-09-02 08:06 UTC
I suspected RunnerUp to make measuring mistakes.

To proof it, yesterday I started my workout on a track that has kilometer marks and is exactly 4 km long. I started the record at the beginning of the track, ran to the 4 km mark and then back to km=1. I took care not to make any detours so the whole record should be more or less exactly 7 km. RunnerUp however recorded 7541 m, which is quite a big deviation.

Needless to say that therefore also the speed calculations can't be right...

If you tell me the way to extract the record from my phone, I will happily upload it.

**Comment by jonasoreland** [comment] 2015-09-02 08:19
Hi there,
RunnerUp currently does no GPS filtering/interpretation but trusts what your hardware/phone reports.
If you want better precision you need to run with better GPS signal or buy a newer phone.

There has been discussion about adding GPS filtering...e.g https://github.com/jonasoreland/runnerup/issues/257. But so far nothing has been done.

wdyt ?

**Comment by speendo** [comment] 2015-09-03 15:19
Hello and thank you for your quick answer!
Actually, my hardware isn't that old (a Oneplus One) and the track doesn't even look too noisy on the map.

Still, there is some "jumping", when I zoom in, so your explanation could likely be right. I just looked on a way to implement GPS smoothing. I found out that a [Kalman-Filter](http://stackoverflow.com/questions/1134579/smooth-gps-data) would probably be the right approach.

I cannot tell how hard it might be to use, but I found a Kalman filter in OpenCV (find it [here](http://docs.opencv.org/master/dd/d6a/classcv_1_1KalmanFilter.html#gsc.tab=0)). Another library I found is [this](http://sourceforge.net/projects/jkalman) one.

It might be a great enhancement. I would try to implement it myself but, although I learned to code some Java, an Android app might be beyond my skills...

**Comment by CharString** [comment] 2015-09-17 05:50
With "newer", he probably meant better:

    Appeal to Novelty
    
    Supposing something is better because it is new or newer.
    
    'Awesome! The latest version of this operating system is going to make my computer faster and better..'

-- From Logical Defence Application

And newer != better seems to be the case in GPS chipsets, according to this research http://fellrnr.com/wiki/GPS_Accuracy

Looks to me it's safe to close this issue as a duplicate of #257.

**Comment by spitters** [comment] 2016-06-09 12:00
I have a similar experience on a run with google my tracks and runnerup. 
Runnerup seems to give longer distances than my tracks (now deprecated). 
I don't fully understand how this relates to @jonasoreland statement that you are just using the GPS hardware.

**Comment by gerhardol** [comment] 2017-08-09 16:35
RU takes uses the GPS points as supplied by the GPS HW
You often get better accuracy by decreasing the update frequency

**Closed by gerhardol** 2017-08-09 16:35 UTC
Labels: duplicate
