### ISSUE TITLE
cadence stopped recording

### ISSUE THREAD

**Issue by dpadgett** [jonasoreland/runnerup#1160] opened 2023-08-21 23:15 UTC
hi, this app used to record cadence on my runs.  i had to reimage my phone, and the app restored its settings when it was reinstalled.  however, now cadence is not recorded despite the setting being enabled.  phone is pixel 7 pro.  the sensor is still working because it can be recorded using the strava app.

**Comment by gerhardol** [comment] 2023-08-22 22:18
RU measures cadence with the step sensor. If it is not recorded, it may be that Android do not expect the sensor to be queried so often as now. There is no change in the app.
There are no specific rules for sensor access here (that I have found). Maybe the sensor need to be queried less often, which means that updates will be slower.

Strava may determine cadence with slower access or by using the gyro or so.

**Comment by dpadgett** [comment] 2023-09-01 17:09
i found today that the audio cues from RU does contain RPM.  but the gpx / tcx of the activity saved doesn't include it.  so it seems like the sensor is working but somehow RU didn't save the data into the file.

**Comment by dpadgett** [comment] 2023-09-01 19:29
i dug in some more and the values actually are recorded in the file.  they are just dropped by strava on importing the tcx.  manually uploading a gpx format export worked.

**Comment by gerhardol** [comment] 2023-09-01 20:17
Duplicate of #1161

**Closed** 2024-06-08 20:07 UTC
