### ISSUE TITLE
Multiple workout types extension

### ISSUE THREAD

**Issue by mloskot** [jonasoreland/runnerup#10] opened 2013-08-02 09:37 UTC
This issue is not a feature request or bug report, but rather a discussion thread (there seem to be no mailing list).

Is there any plan or interest to extend the RunnerUp to support multiple types of workouts, not only running or biking? 

It would be great to have an open source general fitness manager app and the RunnerUp seems to be a great candidate for such project.
It could be similar to the Web-based Funbeat service, where workouts can be customised and composed from individual exercises with attributes like sets, reps, weight, time, equipment, etc.

**Comment by gerhardol** [comment] 2017-08-09 19:48
Settin as duplicate of #533 
This issue has some further requests, but it is old

**Closed by gerhardol** 2017-08-09 19:48 UTC
Labels: duplicate, enhancement
