### ISSUE TITLE
Feature Request: Pebble Support

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#316] opened 2015-08-28 16:06 UTC
I have seen other comments in the App Store feedback relating to this.  I use my Pebble with RunKeeper, etc. and being able to glance at your Distance and Pace is great during training.  Although the Audio Cues in RunnerUp are brilliant, Pebble Support would be a real plus.

**Comment by RunningCl0ud** [comment] 2015-08-30 08:51
I could not agree more @Cagier . You can read more in Feature Request #98

**Comment by jonasoreland** [comment] 2015-09-05 11:21
duplicate of #98

**Closed by jonasoreland** 2015-09-05 11:21 UTC
