### ISSUE TITLE
Linking with Strava not working

### ISSUE THREAD

**Issue by vojtechhuser** [jonasoreland/runnerup#911] opened 2020-04-28 00:18 UTC
if a user logs in to strava via `Login using Google` (not email and psw) - the app gives error that such authentication is not allowed

Error 403: Disallowed_useragent   (text refers you to use browser), but that seems not an option (like open in browser) (since it opens within app browser like interface)

**Comment by gerhardol** [comment] 2020-04-28 08:15
Duplicate of #791 

Some rewriting needed to support Login with Google, but there is a workaround

**Closed by gerhardol** 2020-04-28 08:15 UTC
