### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [jonasoreland/runnerup#643] opened 2018-02-23 10:39 UTC
After a double rotation of the AccountListActivity there are in heap memory 2 instances more of:

class org.runnerup.view.AccountListActivity$1 @ 0x12ca6e80
class org.runnerup.view.AccountListActivity$2 @ 0x12ca6f40
class org.runnerup.view.AccountListActivity @ 0x12cd9000

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onCreate-onDestroy lifecycle. 

I have encountered this problem on an Android emulator running 7.1.1 os version.

**Comment by gerhardol** [comment] 2018-08-01 14:35
I cannot see any obvious problem in the code.
In master, there has been some cleanups, for instance has the list been moved to a local variable and "view holder pattern" has been applied in other views, so it should at least not be worse.

**Comment by gerhardol** [comment] 2020-08-23 19:30
Duplicate of #862

**Closed by gerhardol** 2020-08-23 19:30 UTC
Labels: bug
