### ISSUE TITLE
Import Backup from selectable location

### ISSUE THREAD

**Issue by nottheend** [jonasoreland/runnerup#1022] opened 2021-05-15 18:04 UTC
Hi, thanks for building the app.

I'm currently on Android 11 and it seems to be impossible without rooted device to move any backup within the expected data folder of the app.

It would be nice if the backup file could be selected from a different location too.

Thanks

**Comment by gerhardol** [comment] 2021-05-15 18:14
Duplicate of #999 
Scoped storage in Android 10+ prevents usage outside app specific directories.
To change this you need special privileges, which is only granted to very specific apps.

**Closed by gerhardol** 2021-05-15 18:14 UTC

**Comment by nottheend** [comment] 2021-05-15 20:21
Thanks for clarifying!
