### ISSUE TITLE
[Feature request] Configurable audio cues by sport

### ISSUE THREAD

**Issue by Almorca** [jonasoreland/runnerup#368] opened 2016-02-18 16:11 UTC
Keep audio cues by sport so when I start a sport activity Runnerup use the cues that this sport have associate.

The background of this request is to have audio cues for running and not for biking and configure that automatically.

**Comment by jonasoreland** [comment] 2016-04-24 22:50
duplicate of #27

**Closed by jonasoreland** 2016-04-24 22:50 UTC
