### ISSUE TITLE
Feature Request: Manual choose language in Settings.

### ISSUE THREAD

**Issue by Mixb** [jonasoreland/runnerup#190] opened 2015-02-11 17:24 UTC
Need to be able to manual choose language in Settings. Many Russian-speaking users are accustomed to the English language in fitness applications, as a long time had no alternatives.

**Comment by jonasoreland** [comment] 2015-02-11 17:53
this is a duplicate of issue #136, right ?
if YES, then close this.
if NO explain why

/Jonas

**Comment by Mixb** [comment] 2015-02-11 18:35
Yes, early I saw this post, but I thought that it in the comments.

**Comment by jonasoreland** [comment] 2015-02-22 18:11
let this one can be for audio and #136 for gui.
so this is fixed.

**Closed by jonasoreland** 2015-02-22 18:11 UTC
